// scripts/editorial/write.ts
// Phase 50 — atomic temp+rename writer + optional dual-write mirror (WRIT-03..05).
// Phase 51 — findings-scaffold emission (EDIT-05): idempotent seed of
//   site-editorial-findings.md next to the capture artifact.
// SCAF-08 forbidden in this directory (see .planning/REQUIREMENTS.md SCAF-08):
//   - path-alias imports (use relative paths)
//   - non-deterministic timestamp APIs (use injected/fixed timestamps)
//   - platform-specific line endings (use literal newline only)
//   - parallel iteration over the ordered route list (use sequential for-of)

import { constants as fsConstants } from 'node:fs'
import * as fsp from 'node:fs/promises'
import * as nodePath from 'node:path'
import type { EditorialConfig } from './config.ts'

const MIRROR_RELATIVE_PATH = '.planning/research/site-editorial-capture.md'

const FINDINGS_SCAFFOLD_FILENAME = 'site-editorial-findings.md'

/**
 * SCAFFOLD_TEMPLATE — the locked seed content for `site-editorial-findings.md`.
 *
 * Emitted once by `emitFindingsScaffold` on first capture run (never
 * overwrites Dan's in-progress findings). Five section headings, three
 * priority label strings, three career positioning doc references locked
 * per 51-CONTEXT.md. Literal `\n` line endings only — SCAF-08 discipline
 * forbids platform-specific EOL constants in this directory.
 */
export const SCAFFOLD_TEMPLATE =
  '# Site Editorial Findings\n' +
  '\n' +
  '**Scaffold auto-generated by editorial-capture.** Populate each section below\n' +
  'using the corresponding captured content in `site-editorial-capture.md`.\n' +
  '\n' +
  'Cross-reference these career positioning docs where relevant:\n' +
  '- `career/reference-data/design-philosophy-essay.md`\n' +
  '- `career-values-reference.md`\n' +
  '- `case-study-gp-accessibility-signoff.md`\n' +
  '\n' +
  'Priority labels: `blocker` / `should-fix` / `nice-to-have`.\n' +
  '\n' +
  '---\n' +
  '\n' +
  '## Inconsistencies\n' +
  '\n' +
  '<!-- Items where the captured content contradicts itself or drifts from canonical data. -->\n' +
  '\n' +
  '## Structural\n' +
  '\n' +
  '<!-- Issues with page layout, nav, information architecture, or content hierarchy. -->\n' +
  '\n' +
  '## Copy\n' +
  '\n' +
  '<!-- Wording, tone, typos, jargon, readability concerns. -->\n' +
  '\n' +
  '## Alignment Gaps\n' +
  '\n' +
  '<!-- Places where the site diverges from career positioning docs — cite the source doc per entry. -->\n' +
  '\n' +
  '## Open Questions\n' +
  '\n' +
  '<!-- Items needing clarification before the v9.0 direction decision. -->\n'

/**
 * atomicWrite — write content to a PID-suffixed temp file, then rename
 * over the destination. The rename is atomic on POSIX (and WSL is POSIX),
 * so concurrent readers (e.g., Obsidian's filewatcher) never observe a
 * half-written file.
 *
 * WRIT-03: UTF-8 encoding explicit; literal-newline-only line endings are
 * the caller's responsibility (Phase 50 document assembler emits native
 * line endings). This function does not transform line endings.
 *
 * On write or rename failure, the temp file is best-effort removed so
 * accidental re-runs don't accumulate stale sibling temp files.
 */
export async function atomicWrite(absPath: string, content: string): Promise<void> {
  const temp = `${absPath}.tmp-${process.pid}`
  try {
    await fsp.writeFile(temp, content, { encoding: 'utf8' })
    await fsp.rename(temp, absPath)
  } catch (err) {
    await fsp.unlink(temp).catch(() => undefined)
    throw err
  }
}

/**
 * writePrimaryAndMirror — always writes the primary output file; optionally
 * mirrors the same content to `.planning/research/site-editorial-capture.md`
 * when `config.mirror === true`.
 *
 * Primary write failure rejects the whole function (primary is load-bearing).
 * Mirror write failure is logged to stderr and silently absorbed —
 * the mirror is OPTIONAL per WRIT-05, and losing the repo-scoped copy
 * should not fail an otherwise-successful capture run.
 *
 * Returns the absolute path of each file actually written. `mirrorPath`
 * is undefined when mirror was not requested OR when the mirror write
 * failed.
 */
export async function writePrimaryAndMirror(
  config: EditorialConfig,
  content: string,
): Promise<{ readonly primaryPath: string; readonly mirrorPath?: string }> {
  await atomicWrite(config.outputPath, content)

  if (config.mirror !== true) {
    return { primaryPath: config.outputPath }
  }

  const mirrorPath = nodePath.resolve(process.cwd(), MIRROR_RELATIVE_PATH)
  try {
    await fsp.mkdir(nodePath.dirname(mirrorPath), { recursive: true })
    await atomicWrite(mirrorPath, content)
    return { primaryPath: config.outputPath, mirrorPath }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    process.stderr.write(`[editorial-capture] mirror write failed: ${message}\n`)
    return { primaryPath: config.outputPath }
  }
}

/**
 * emitFindingsScaffold — first-run seed of `site-editorial-findings.md`
 * placed next to the capture artifact (EDIT-05, Phase 51).
 *
 * Idempotency contract (load-bearing): if the scaffold file already exists,
 * this function returns `null` WITHOUT writing — Dan's in-progress findings
 * must survive every subsequent capture run. Only the absent-file branch
 * writes; the existence probe is `fsp.access(path, F_OK)` (throws when
 * absent, caught by the scaffold-write branch).
 *
 * Failure modes (any fsp error during writeFile) propagate up; the caller
 * in `index.ts main()` wraps the invocation in `.catch()` so scaffold
 * emission is non-fatal to the overall capture run.
 *
 * Returns the absolute scaffold path on successful write, or `null` when
 * the file already existed and emission was skipped.
 */
export async function emitFindingsScaffold(
  captureOutputPath: string,
): Promise<string | null> {
  const scaffoldPath = nodePath.join(
    nodePath.dirname(captureOutputPath),
    FINDINGS_SCAFFOLD_FILENAME,
  )
  try {
    await fsp.access(scaffoldPath, fsConstants.F_OK)
    // File already exists — preserve Dan's findings, skip silently.
    return null
  } catch {
    await fsp.writeFile(scaffoldPath, SCAFFOLD_TEMPLATE, { encoding: 'utf8' })
    return scaffoldPath
  }
}
