// scripts/markdown-export/index.ts
// Phase 38 placeholder — real orchestrator is wired in Phase 43 (ORCH-01).
// Path aliases and application-source imports are forbidden inside this directory
// (see PROJECT.md forbidden list); tsconfig.scripts.json enforces this via empty paths.

const GENERATED_BANNER = '<!-- auto-generated by scripts/markdown-export — do not edit by hand -->'

function main(): void {
  // Intentionally empty: Phase 38 only ships primitives, escape helpers,
  // frontmatter serializer, and IR types. Phase 39 adds extractors, Phase 41/42
  // add renderers, Phase 43 wires this orchestrator.
  process.stdout.write(`${GENERATED_BANNER}\n`)
}

main()
